---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: ${{secrets.TIMEZONE1}}/${{secrets.TIMEZONE2}}
    labels:
      - "docker dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      day: "friday"
      time: "00:00"
      timezone: "Europe/Berlin"
    labels:
      - "github-actions dependencies"
