--- 
ignore: |
  .github/workflows/*
rules: 
  braces: 
    level: warning
    max-spaces-inside: 0
    max-spaces-inside-empty: 5
    min-spaces-inside: 0
    min-spaces-inside-empty: 1
  brackets: 
    level: warning
    max-spaces-inside: 0
    max-spaces-inside-empty: 5
    min-spaces-inside: 0
    min-spaces-inside-empty: 1
  colons: 
    level: warning
    max-spaces-after: 1
    max-spaces-before: 0
  commas: 
    level: warning
    max-spaces-after: 1
    max-spaces-before: 0
    min-spaces-after: 1
  comments: disable
  comments-indentation: disable
  document-end: disable
  document-start: 
    level: warning
    present: true
  empty-lines: 
    level: warning
    max: 2
    max-end: 0
    max-start: 0
  hyphens: 
    level: warning
    max-spaces-after: 1
  indentation: 
    check-multi-line-strings: false
    indent-sequences: true
    level: warning
    spaces: consistent
  key-duplicates: enable
  line-length: 
    allow-non-breakable-inline-mappings: true
    allow-non-breakable-words: true
    level: warning
    max: 80
  new-line-at-end-of-file: disable
  new-lines: 
    type: unix
  trailing-spaces: disable
