ARG VARIANT=focal
FROM docker.io/library/ubuntu:$VARIANT

RUN apt-get update; \
    apt-get install --no-install-recommends --assume-yes \
    ca-certificates \
    curl; \
    apt-get clean && rm -fr /var/lib/apt/lists/*
