---
name: Container Build & Push

on:
  push:
    branches:
      - "main"
    # paths:
    #   - "Dockerfile"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  skip-duplicate-actions:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: true
          concurrent_skipping: never

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/workflows/Dockerfile1.test
          load: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/test2:${{ github.sha }}

      - name: Test
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/test2:${{ github.sha }}

  dockerhub-push:
    needs: test
    runs-on: ubuntu-latest
    # steps:
    #   - name: Set up QEMU
    #     uses: docker/setup-qemu-action@v2

    #   - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v2

    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

    #   - name: Build and push to Docker Hub
    #     uses: docker/build-push-action@v4
    #     with:
    #       context: .
    #       file: ./Dockerfile
    #       push: true
    #       tags: |
    #         ${{ secrets.DOCKERHUB_USERNAME }}/test2:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/workflows/Dockerfile1.test
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/test2:latest
