---
name: Container Build & Push

on:
  push:
    branches:
      - "main"
    paths:
      # - "/.devcontainer/Containerfile"
      # - "/workflows/.devcontainer/Containerfile.*"
      # - "Containerfile"
      # - "Dockerfile.*"
      - "Dockerfile"
      # - "Dockerfile.test"
      # - ".github/workflows/Dockerfile1.test"
  pull_request:
    branches:
      - "main"
    paths:
      # - ".devcontainer/Containerfile"
      # - ".devcontainer/Containerfile.*"
      # - "/.devcontainer/Containerfile*"
      # - "/workflows/.devcontainer/Containerfile.*"
      # - "Containerfile"
      # - "Dockerfile.*"
      - "Dockerfile"
      # - "Dockerfile.test"
      # - ".github/workflows/Dockerfile1.test"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  skip-duplicate-actions:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: true
          concurrent_skipping: never

  lint:
    name: Hadolint Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile

  docker-hub:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: lint
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/test2:latest

  # azure-container-registry:
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   runs-on: ubuntu-latest
  #   environment: acr
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Login to ACR
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  #         username: ${{ secrets.REGISTRY_USERNAME }}
  #         password: ${{ secrets.REGISTRY_PASSWORD }}

  #     - name: Build and push to ACR
  #       uses: docker/build-push-action@v3
  #       with:
  #         file: ./Dockerfile.test
  #         push: true
  #         tags: |
  #           ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.NAMESPACE }}/${{ secrets.REPOSITORY }}:latest
