---
name: Containerfile Lint

on:
  push:
    branches:
      - "main"
    paths:
      - "Containerfile"
      - "Dockerfile"
      - "Dockerfile.*"
  pull_request:
    branches:
      - "main"
    paths:
      - "Containerfile"
      - "Dockerfile"
      - "Dockerfile.*"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  skip-duplicate-actions:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: true
          concurrent_skipping: never

  lint:
    name: Hadolint Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile.test

  scan:
    name: Scan config files for vulnerabilities
    runs-on: ubuntu-latest
    container:
      image: docker.io/aquasec/trivy:0.23.0
      volumes:
        - "${{ github.workspace }}:/volume"
    steps:
      - name: Scan config Containerfiles for vulnerabilities
        run: |
          # trivy config --file-patterns "dockerfile:Containerfile" /volume
          pwd
          ls -la
